apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeling.fullname" . }}
  labels:
    {{- include "kubeling.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kubeling.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubeling.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubeling.serviceAccountName" . }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          args:
            - --leader-elect={{ .Values.leaderElection.enabled }}
            - --leader-elect-namespace={{ .Values.leaderElection.namespace }}
            - --leader-elect-lease-name={{ .Values.leaderElection.leaseName }}
            - --resync-period={{ .Values.resyncPeriod }}
            - --workers={{ .Values.workers }}
            - --health-addr=:{{ .Values.healthz.port }}
            {{- with .Values.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- $configMapRef := .Values.configMap }}
          {{- if .Values.config }}
          {{- $configMapRef = include "kubeling.configMapName" . }}
          {{- end }}
          {{- with $configMapRef }}
          env:
            - name: CONFIGMAP
              value: {{ . | quote }}
          {{- end }}
          ports:
            - name: healthz
              containerPort: {{ .Values.healthz.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
              host: 127.0.0.1
            initialDelaySeconds: 10
            periodSeconds: 10
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
